[package]
name = "cs50_os"
version = "0.1.0"
edition = "2018"
authors = ["Michael Yermonsky <mikeyermonsky@yahoo.com>"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
